# Generated by Django 3.1.6 on 2021-02-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20210214_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='used_times',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
